# Generated by Django 3.2.6 on 2021-09-26 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_ClubAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=60, verbose_name='Event Title')),
                ('description', models.TextField(max_length=1000)),
                ('venue', models.CharField(max_length=60)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('fee_required', models.BooleanField(blank=True, default=False)),
                ('registration_fee', models.FloatField(blank=True, default=0.0)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('registration_status', models.BooleanField(default=False)),
                ('event_banner', models.ImageField(upload_to='Event/%Y/%m/%d/')),
                ('event_link', models.URLField(blank=True, max_length=100, null=True)),
                ('event_fb_link', models.URLField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('clubadmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubadmin_event_created', to='App_ClubAdmin.clubadmin')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_photo', models.ImageField(blank=True, upload_to='EventsPhoto/%Y/%m/%d/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_photo', to='App_Event.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_notice', models.TextField(max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_notice', to='App_Event.event')),
            ],
        ),
    ]
