# Generated by Django 3.2.6 on 2021-09-26 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='clubadmin',
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clubadmin_event_created', to='App_ClubAdmin.user'),
            preserve_default=False,
        ),
    ]
