# Generated by Django 3.2.6 on 2021-10-05 00:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App_Event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventnotice',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='eventnotice',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 5, 0, 55, 2, 119920, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
