# Generated by Django 3.2.6 on 2021-10-05 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registration_status',
        ),
    ]
