# Generated by Django 3.2.6 on 2021-10-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Event', '0002_auto_20211001_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_title',
            field=models.CharField(max_length=150, verbose_name='Event Title'),
        ),
    ]
