# Generated by Django 3.2.6 on 2021-09-30 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Volunteer', '0002_remove_volunteer_event'),
        ('App_Event', '0002_auto_20210925_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_volunteer', to='App_Event.event')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_volunteers', to='App_Volunteer.volunteer')),
            ],
        ),
    ]
