# Generated by Django 3.2.6 on 2021-09-30 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Volunteer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='event',
        ),
    ]
